contract_generator/urls.py
from django.urls import path

from contract_generator.views import new_client_contract, new_clausule, new_item, list_generated_contracts, \
    edit_generated_contracts, detail_generated_contract, ContractToPdf, adjust_values, list_items, edit_item, \
    list_clausules, edit_clausule, delete_gen_contract, delete_item, delete_clausule


urlpatterns = [
    # Create
    path('newct/', new_client_contract, name='new_client_contract'),
    path('newcl/', new_clausule, name='new_clausule'),
    path('newit/', new_item, name='new_item'),


    # List
    path('', list_generated_contracts, name='list_generated_contracts'),
    path('items/', list_items, name='list_items'),
    path('clausules/', list_clausules, name='list_clausules'),


    # Detail
    path('detailct/<int:id>', detail_generated_contract, name='detail_generated_contract'),


    # Edit
    path('editct/<int:id>', edit_generated_contracts, name='edit_generated_contracts'),
    path('editit/<int:id>', edit_item, name='edit_item'),
    path('editcl/<int:id>', edit_clausule, name='edit_clausule'),
    path('adjust_values/<int:id>', adjust_values, name='adjust_values'),


    # Delete
    path('deletect/<int:id>', delete_gen_contract, name='delete_gen_contract'),
    path('deleteit/<int:id>', delete_item, name='delete_item'),
    path('deletecl/<int:id>', delete_clausule, name='delete_clausule'),

    # Generate contract PDF
    path('contractpdf/<int:id>', ContractToPdf.as_view(), name='contract_to_pdf'),
]

crmProj/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import urls as clients_urls
from home import urls as home_urls
from accounts import urls as accounts_urls
from contracts import urls as contract_urls
from agenda import urls as agenda_urls
from dashboard import urls as dashboard_urls
from contract_generator import urls as contractgen_urls
from company_profile import urls as company_profile_urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Home
    path('', include(home_urls)),

    # Dash
    path('dashboard/', include(dashboard_urls)),

    path('register/', include(accounts_urls)),
    path('contracts/', include(contract_urls)),
    path('agenda/', include(agenda_urls)),

    # Login and logout
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout'),

    # Client application urls
    path('client/', include(clients_urls)),
    path('admin/', admin.site.urls),

    # Contract generator urls
    path('contractgen/', include(contractgen_urls)),

    # Company profile urls
    path('profile/', include(company_profile_urls)),

]

home/urls.py
from django.urls import path
from .views import home #, register_page

urlpatterns = [
    path('', home, name='home'),
    #path('register/', register_page, name='register_page'),
]

contract_generator/models.py
from django.conf import settings
from django.db import models

from clients.models import ClientPerson, ClientCompany
from contracts.models import Contract

User = settings.AUTH_USER_MODEL


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    contract = models.ForeignKey(Contract, blank=True, null=True, on_delete=models.CASCADE)

    item_name = models.CharField(max_length=90)

    item_value = models.FloatField(blank=True, null=True, max_length=12)
    item_qt = models.FloatField(blank=True, null=True, max_length=12)

    # Unity options
    METERS = 'MT'
    LITERS = 'LT'
    NOT_APPLY = '-'
    UNITY_CHOICES = [
        (METERS, 'Metros'),
        (LITERS, 'Litros'),
        (NOT_APPLY, '-'),
    ]

    unity = models.CharField(choices=UNITY_CHOICES, default=METERS, max_length=20)

    # Type options
    EQUIPMENT = 'Equipamento'
    LABOR = 'Mão de obra'
    MATERIAL = 'Material'
    TYPE_CHOICES = [
        (EQUIPMENT, 'Equipamento'),
        (LABOR, 'Mão de obra'),
        (MATERIAL, 'Material'),
    ]

    item_type = models.CharField(choices=TYPE_CHOICES, default=MATERIAL, max_length=20)


    def __str__(self):
        return self.item_name


class Clausule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    clausule_name = models.CharField(max_length=60)
    clausule_type = models.CharField(max_length=60)

    clausule_description = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.clausule_name




class ClientContract(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    work_order = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True, blank=True)
    contract_name = models.CharField(max_length=60)
    address = models.TextField(blank=True, null=True)

    # Value related information
    total_value = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2)
    installments = models.IntegerField(null=True, blank=True)

    # Items and clausules of the contract
    items = models.ManyToManyField(Item, blank=True, null=True)
    clausules = models.ManyToManyField(Clausule, blank=True, null=True)

    # Company associated with the contract
    company_client = models.ForeignKey(ClientCompany,blank=True, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.contract_name

contract_generator/views.py
from datetime import date

from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from company_profile.models import CompanyProfile
from contract_generator.filters import ItemFilter, ContractFilter, ClausuleFilter
from contract_generator.forms import ClientContractForm, ClausuleForm, ItemForm, ItemFormSimple
from contract_generator.models import ClientContract, Item, Clausule

from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from xhtml2pdf import pisa

from contracts.models import Contract
from crmProj.settings import STATIC_ROOT

from crmProj import settings

"""
ADD A NEW CONTRACT
"""
@login_required
def new_client_contract(request):
    user = request.user
    form = ClientContractForm(request.POST or None, request.FILES or None, user=user)

    if form.is_valid():
        contract = form.save(commit=False)
        contract.user = request.user
        contract.save()

        selected_clausules_ids = request.POST.getlist('clausules')
        contract.clausules.set(selected_clausules_ids)
        # Suponhamos que o campo 'items' do formulário seja uma lista de IDs dos itens selecionados
        selected_items_ids = request.POST.getlist('items')
        contract.items.set(selected_items_ids)
        contract.save()

        return redirect('list_generated_contracts')
    return render(request, 'client_contract_form.html', {'form': form})


"""
ADD A NEW ITEM
"""
@login_required
def new_item(request):
    user = request.user

    form = ItemFormSimple(request.POST or None, request.FILES or None, user=user)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        return redirect('list_items')
    return render(request, 'item_form.html', {'form': form})


"""
ADD A NEW CLAUSULE
"""
@login_required
def new_clausule(request):
    user = request.user

    form = ClausuleForm(request.POST or None, request.FILES or None, user=user)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        return redirect('list_clausules')
    return render(request, 'clausule_form.html', {'form': form})



"""
LIST THE GENERATED CONTRACTS
"""
@login_required
def list_generated_contracts(request):
    contracts = ClientContract.objects.filter(user=request.user)
    contracts_count = ClientContract.objects.filter(user=request.user).count()

    contract_filter = ContractFilter(request.GET, queryset=contracts)

    # total_value = ClientContract.work_order.objects.filter(user=request.user).aggregate(sum=Sum('value'))['sum'] or 0

    total_value = 0
    for contract in contracts:
        total_value += Contract.objects.filter(user=request.user, clientcontract=contract).aggregate(sum=Sum('value'))['sum'] or 0


    today = date.today()
    return render(request, 'list_generated_contracts.html', {'contracts': contracts,
                                                  'contracts_count': contracts_count,
                                                  'total_value': total_value,
                                                  'contract_filter': contract_filter,
                                                  'today':today
                                                  })


"""
LIST THE ITEMS
"""
@login_required
def list_items(request):
    items = Item.objects.filter(user=request.user)
    items_count = Item.objects.filter(user=request.user).count()

    item_filter = ItemFilter(request.GET, queryset=items)

    return render(request, 'list_items.html', {'items': items,
                                                  'items_count': items_count,
                                                  'item_filter': item_filter
                                                  })

"""
LIST THE CLAUSULES
"""
@login_required
def list_clausules(request):
    clausules = Clausule.objects.filter(user=request.user)
    clausules_count = Clausule.objects.filter(user=request.user).count()

    clausule_filter = ClausuleFilter(request.GET, queryset=clausules)

    return render(request, 'list_clausules.html', {'clausules': clausules,
                                                  'clausules_count': clausules_count,
                                                  'clausule_filter': clausule_filter
                                                  })

"""
EDIT THE CONTRACT
"""
@login_required
def edit_generated_contracts(request, id):
    contract = get_object_or_404(ClientContract, pk=id)
    user = request.user

    form = ClientContractForm(request.POST or None, request.FILES or None, instance=contract, user=user)

    if form.is_valid():
        form.save()
        return redirect('list_generated_contracts')
    return render(request, 'client_contract_form.html', {'form': form,
                                                         'contract': contract
                                                         })
"""
EDIT ITEMS OF THE CONTRACT
"""
@login_required
def edit_item(request, id):
    item = get_object_or_404(Item, pk=id)
    user = request.user

    form = ItemFormSimple(request.POST or None, request.FILES or None, instance=item, user=user)

    if form.is_valid():
        form.save()
        return redirect('list_items')
    return render(request, 'item_form.html', {'form': form,
                                                         'item': item
                                                         })


"""
EDIT CLAUSULES OF THE CONTRACT
"""
@login_required
def edit_clausule(request, id):
    clausule = get_object_or_404(Clausule, pk=id)
    user = request.user

    form = ClausuleForm(request.POST or None, request.FILES or None, instance=clausule, user=user)

    if form.is_valid():
        form.save()
        return redirect('list_clausules')
    return render(request, 'clausule_form.html', {'form': form,
                                                         'clausule': clausule
                                                         })


"""
DETAIL GENERATE CONTRACT
"""
@login_required
def detail_generated_contract(request, id):
    contract = get_object_or_404(ClientContract.objects.filter(user=request.user), pk=id)
    company_profile = get_object_or_404(CompanyProfile.objects.filter(user=request.user))
    contract_clausules = contract.clausules.all()
    contract_items = contract.items.all()

    print(company_profile)
    total = 0
    for item in contract_items:
        item_total_qt = item.item_qt or 0
        item_total_value = item.item_value or 0
        total += item_total_qt * item_total_value


    context = {'contract': contract,
               'contract_clausules': contract_clausules,
               'contract_items': contract_items,
               'company_profile': company_profile,
               'total': total,
    }

    return render(request, 'detail_generated_contract.html', context)





"""
ADJUST THE VALUES ON THE GENERATED CONTRACTS
"""
@login_required
def adjust_values(request, id):
    item = get_object_or_404(Item, pk=id)
    # Using instance, the form already start with the data from the client received
    form = ItemForm(request.POST or None, request.FILES or None, instance=item)

    # Get the contract that sent the user to the adjustment page
    if request.method == 'GET':
        request.session['last_contract'] = request.META.get('HTTP_REFERER', '/')

    if form.is_valid():
        form.save()
        # Redirect the user to the contract that sent the user to the adjustment page
        return HttpResponseRedirect(request.session['last_contract'])
    return render(request, 'item_form.html', {'form': form, 'item': item})



"""
DELETE GENERATED CONTRACT
"""
@login_required
def delete_gen_contract(request, id):
    contract = get_object_or_404(ClientContract, pk=id)

    if request.method == 'POST':
        contract.delete()
        return redirect('list_generated_contracts')

    return render(request, 'deletion_gen_contract_confirm.html', {'contract': contract})




"""
DELETE ITEM
"""
@login_required
def delete_item(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == 'POST':
        item.delete()
        return redirect('list_items')

    return render(request, 'deletion_item_confirm.html', {'item': item})




"""
DELETE CLAUSULE
"""
@login_required
def delete_clausule(request, id):
    clausule = get_object_or_404(Clausule, pk=id)

    if request.method == 'POST':
        clausule.delete()
        return redirect('list_clausules')

    return render(request, 'deletion_clausule_confirm.html', {'clausule': clausule})



"""
GENERATE CONTRACT PDF
"""
class ContractToPdf(View):
    def get(self, request, *args, **kwargs):
        template_path = 'generated_contract.html'
        template = get_template(template_path)

        company_profile = get_object_or_404(CompanyProfile.objects.filter(user=request.user))

        contract = ClientContract.objects.get(pk=self.kwargs['id'])
        contract_items = contract.items.all()

        profile = CompanyProfile.objects.filter(user=request.user).first()

        color = 'red;'

        total = 0
        for item in contract_items:
            item_total_qt = item.item_qt or 0
            item_total_value = item.item_value or 0
            total += item_total_qt * item_total_value

        def get_queryset(self):
            owner = get_object_or_404(ClientContract.objects.filter(user=self.request.user, pk=self.kwargs['id']))
            return owner.user.full_name

        counter = 0
        context = {
            'contract': ClientContract.objects.get(pk=self.kwargs['id']),
            'contract_items': ClientContract.objects.get(pk=self.kwargs['id']).items.all(),
            'contract_clausules': ClientContract.objects.get(pk=self.kwargs['id']).clausules.all(),

contract_generator/templates/clausule_form.html
{% extends 'base.html' %}

{% block main %}
<div class="container">

        <div class="container-form">

            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn-confirm">Confirmar</button>
            </form>
        </div>


        <div class="container-descript">
            <h2 class="h2-containter">Gere seu contrato aqui!</h2>
            <img src="https://i.ibb.co/pX0bq35/Illustration.png" class="img-form">

        </div>

</div>
{% endblock %}

contract_generator/templates/client_contract_form.html
{% extends 'base.html' %}

{% block main %}
<div class="container">

        <div class="container-form">

            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn-confirm">Confirmar</button>
            </form>
        </div>


        <div class="container-descript">
            <h2 class="h2-containter">Gere seu contrato aqui!</h2>
            <img src="https://i.ibb.co/pX0bq35/Illustration.png" class="img-form">

        </div>

</div>
{% endblock %}

contract_generator/templates/deletion_clausule_confirm.html
{% extends 'base.html' %}

{% block main %}

    {% if user.id == clausule.user.id %}

        <h1>Você gostaria de deletar {{ clausule.clausule_name }} ?</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit">Deletar</button>
        </form>
        <br>
        <a href="{% url 'contract_list' %}"><button>Cancelar</button></a>

    {% else %}
        <h2>Você não está autorizado a acessar esta página.</h2>
    {% endif %}

{% endblock %}

contract_generator/templates/deletion_gen_contract_confirm.html
{% extends 'base.html' %}

{% block main %}

    {% if user.id == contract.user.id %}

        <h1>Você gostaria de deletar {{ contract.contract_name }} ?</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit">Deletar</button>
        </form>
        <br>
        <a href="{% url 'contract_list' %}"><button>Cancelar</button></a>

    {% else %}
        <h2>Você não está autorizado a acessar esta página</h2>
    {% endif %}

{% endblock %}

contract_generator/templates/deletion_item_confirm.html
{% extends 'base.html' %}

{% block main %}

    {% if user.id == item.user.id %}

        <h1>Você gostaria de deletar {{ item.item_name }} ?</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit">Deletar</button>
        </form>
        <br>
        <a href="{% url 'contract_list' %}"><button>Cancelar</button></a>

    {% else %}
        <h2>Você não está autorizado a acessar esta página</h2>
    {% endif %}

{% endblock %}

contract_generator/templates/detail_generated_contract.html
{% extends 'base.html' %}

{% load mathfilters %}
{% load humanize %}
{% load static %}
{% block title %}Contract detail{% endblock %}
{% block main %}



<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jautocalc@1.3.1/dist/jautocalc.js"></script>



<div class="container-detail">


        <h1 id="detail-pdf">
            {{ contract.work_order.contract_name }}
            <a href="{% url 'edit_generated_contracts' contract.id %}" class="edit-icon right">
                <i class="fa-regular fa-pen-to-square fa-lg"></i>
                <i class="fa-solid fa-pen-to-square fa-lg"></i>
            </a>
        </h1>


        <h2>{{ company_profile.name }}</h2>
        <p><span class="bolded">CNPJ: </span>{{ company_profile.cnpj }}</p>
        <h3 style="text-align: left;">Endereço:</h3>
        <p><span class="bolded">Endereço: </span>{{ company_profile.address }}</p>
        <p><span class="bolded">CEP: </span>{{ company_profile.zipcode }}</p>


        <div><hr class="hr-full"></div>


<!--  DISPLAY THE CLIENT DATA   -->
        <h2>
            Client data:
            <a href="{% url 'edit_contract' contract.work_order.id %}" class="edit-icon right">
                <i class="fa-regular fa-pen-to-square fa-lg"></i>
                <i class="fa-solid fa-pen-to-square fa-lg"></i>
            </a>
        </h2>
        {% if contract.work_order.company_client %}
        <h3 class="subheader">Empresa: </h3>

            <p><span class="bolded">Nome da empresa: </span>{{ contract.work_order.company_client.company_name }}</p>
            <p><span class="bolded">CNPJ: </span>{{ contract.work_order.company_client.company_cnpj }}</p>
            {% if contract.work_order.company_client.phone %}
                <p><span class="bolded">Telefone: </span>{{ contract.work_order.company_client.phone }}</p>
            {% endif %}
            {% if contract.work_order.company_client.email %}
                <p><span class="bolded">Email: </span>{{ contract.work_order.company_client.email }}</p>
            {% endif %}
        {% endif %}
        {% if contract.work_order.person_client %}
        <h3 class="subheader">Pessoa: </h3>
            <p><span class="bolded">Nome: </span>{{ contract.work_order.person_client.fullname }}</p>
            <p><span class="bolded">CPF: </span>{{ contract.work_order.person_client.cpf }}</p>
            {% if contract.work_order.person_client.phone %}
                <p><span class="bolded">Telefone: </span>{{ contract.work_order.person_client.phone }}</p>
            {% endif %}
            {% if contract.work_order.person_client.email %}
                <p><span class="bolded">Email: </span>{{ contract.work_order.person_client.email }}</p>
            {% endif %}
        {% endif %}


    <div><hr class="hr-full"></div>


<!--  CONTRACT DESCRIPTION -->
        <h2>
            Contract description
            <a href="{% url 'edit_contract' contract.work_order.id %}" class="edit-icon right">
                <i class="fa-regular fa-pen-to-square fa-lg"></i>
                <i class="fa-solid fa-pen-to-square fa-lg"></i>
            </a>
        </h2>
        <p>{{ contract.work_order.description }}</p>


    <div><hr class="hr-full"></div>


<!-- DISPLAY ALL THE ITEMS FROM THE CONTRACT -->
        <h2>
            Contract items
            <a href="{% url 'edit_generated_contracts' contract.id %}" class="edit-icon right">
                <i class="fa-regular fa-pen-to-square fa-lg"></i>
                <i class="fa-solid fa-pen-to-square fa-lg"></i>
            </a>
        </h2>

                <table class="client-table" name="item_table">
                    <thead>
                        <tr>
                            <th>Nome do item</th>
                            <th>Valor do item</th>
                            <th>Quantidade</th>
                            <th>Unidade de medida</th>
                            <th>Tipo</th>
                            <th>Total</th>
                            <th>Opções</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for item in contract_items %}
                            {% csrf_token %}
                            <tr class="line_items">
                                <td>{{ item }}</td>
                                <td>R$ {{ item.item_value|floatformat:2|intcomma }}</td>
                                <td>{{ item.item_qt|floatformat:2|intcomma }}</td>
                                <td>{{ item.unity }}</td>
                                <td>{{ item.item_type }}</td>
			                    <td>R$ {{item.item_value|mul:item.item_qt|floatformat:2|intcomma}}</td>

                                <td>
                                    <a href="{% url 'adjust_values' item.id %}"" onclick='overlay()' class="edit-icon">
                                        <i class="fa-regular fa-pen-to-square fa-lg"></i>
                                        <i class="fa-solid fa-pen-to-square fa-lg"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                            <tr>
                                <td class="bolded">Valor total dos intens</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>
                                    R$ {{ total|floatformat:2|intcomma }}
                                </td>
                            </tr>

                    </tbody>
                </table>



<!-- DISPLAY ALL THE CLAUSULES OF THE CONTRACT -->
        <h2>
            Contract clausules
            <a href="{% url 'edit_generated_contracts' contract.id %}" class="edit-icon right">
                <i class="fa-regular fa-pen-to-square fa-lg"></i>
                <i class="fa-solid fa-pen-to-square fa-lg"></i>
            </a>
        </h2>
            <ol>
                {% for clausule in contract_clausules %}
                    <li>{{ clausule }}
                        <ol>
                            <li>{{ clausule.clausule_description }}</li>
                        </ol>
                        <br>
                    </li>
                {% endfor %}
            </ol>

    <div><hr class="hr-full"></div>

<!--    CONTRACT DATES    -->


            <h2>
                Contract dates
                <a href="{% url 'edit_contract' contract.work_order.id %}" class="edit-icon right">
                    <i class="fa-regular fa-pen-to-square fa-lg"></i>
                    <i class="fa-solid fa-pen-to-square fa-lg"></i>
                </a>
            </h2>
            <p><span class="bolded">Início: </span>{{ contract.work_order.starting_date }}</p>
            <p><span class="bolded">Fim: </span>{{ contract.work_order.ending_date }}</p>
            <p><span class="bolded">Data de pagamento: </span>{{ contract.work_order.payment_date }}</p>


<!--    COMPANY SIGNATURE    -->
            <div><hr class="hr-full"></div>


            <h3>Assinaturas</h3>
            <div class="container center">
                <div class="column center">
                    <p class="hr-signature"></p>
                    <span class="bolded">{{ user.full_name }}</span>
                    <span>{{ user }}</span>
                </div>
                <div class="column center">
                    <p class="hr-signature"></p>
                    <span class="bolded">{{ contract.work_order.person_client.first_name }} {{ contract.work_order.person_client.last_name }}</span>
                    <span>{{ contract.work_order.person_client.cpf }}</span>
                </div>
            </div>
            <div class="container center">
                <div class="column center">
                    <p class="hr-signature"></p>
                    <span class="bolded">Testemunha</span>
                </div>
                <div class="column center">
                    <p class="hr-signature"></p>
                    <span class="bolded">Testemunha</span>
                </div>
            </div>




    <!--    PRINT CONTRACT    -->
        <div class="add-new-client-btn" style="margin-bottom:30px; margin-top:30px;">
            <a href="{% url 'contract_to_pdf' contract.id %}" class="new-client-icon" >
                <i class="fa-solid fa-print"></i>
            </a>
            <span class="tooltip">Imprimir</span>
        </div>
</div>

{% endblock %}

contract_generator/templates/item_form.html
{% extends 'base.html' %}

{% block main %}
<div class="container">

        <div class="container-form">

            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn-confirm">Confirmar</button>
            </form>
        </div>


        <div class="container-descript">
            <h2 class="h2-containter">Ajuste o valor dos seus itens aqui!</h2>
            <img src="https://i.ibb.co/pX0bq35/Illustration.png" class="img-form">

        </div>

</div>

{% endblock %}

contract_generator/templates/list_items.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block title %}
Companies List
{% endblock %}


{% block main %}

    <div class="box-row">
        <!-- Active customers -->
        <div class="info-box">
            <h3 class="h3-info-total">Itens totais</h3>
            <h1 class="h1-info-total">{{ items_count }}</h1>
        </div>

    </div>

    <div class="container">
        <div class="container-list">

            <h2>Lista de itens</h2>

            <div>
                <form class="flex right" method="GET">
                        <span class="search-icon">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </span>
                        {{ item_filter.form.item  }}
                        <div class="right">
                            <button class="btn-confirm right">Procurar</button>
                        </div>
                </form>
            </div>

            <table class="client-table">

                <thead>
                    <tr>
                        <th>Nome do item</th>
                        <th>Tipo</th>
                        <th>Unidade</th>
                        <th>Opções</th>
                    </tr>
                </thead>

                <tbody>
                {% for qs in item_filter.qs %}
                    {% for item in items %}
                        {% if item == qs %}
                        <tr>
                            <!-- NAME -->
                            <td>
                                <a href="{% url 'edit_item' item.id %}">{{ item.item_name }}</a>
                            </td>

                            <!-- Item type -->
                            <td>
                                <a href="{% url 'edit_item' item.id %}">
                                    {{ item.get_item_type_display }}
                                </a>
                            </td>

                            <!-- Item unity -->
                            <td>
                                <a href="{% url 'edit_item' item.id %}">{{ item.unity }}</a>
                            </td>


                            <!-- OPTIONS -->
                            <td>
                                <a href="{% url 'edit_item' item.id %}" class="edit-icon">
                                    <i class="fa-regular fa-pen-to-square fa-lg"></i>
                                    <i class="fa-solid fa-pen-to-square fa-lg"></i>
                                </a>

                                <a href="{% url 'delete_item' item.id %}" class="delete-icon">
                                    <i class="fa-regular fa-trash-can fa-lg"></i>
                                    <i class="fa-solid fa-trash-can fa-lg"></i>
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                </tbody>

            </table>

            <div class="add-new-client-btn">
                <a href="{% url 'new_item' %}" class="new-client-icon">
                <i class="fa-solid fa-boxes-packing"></i>
                </a>
                <span class="tooltip">Adicionar item</span>
            </div>

        </div>
    </div>
{% endblock %}